version: 2
jobs:
  node:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - node_modules/*
            - config/*
      - run:
          name: version control
          command: |
              git config user.email $RELEASE_MANAGER_GITHUB_USER_EMAIL
              git config --global user.name $RELEASE_MANAGER_GITHUB_USER_NAME


  android:
    working_directory: /home/circleci/project/android
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout:
          path: /home/circleci/project

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Google Play Key and key store password
          command: |
            ls
            echo -e "\nMYAPP_RELEASE_STORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD\nMYAPP_RELEASE_KEY_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> ./gradle.properties
            echo -e $GOOGLE_PLAY_CREDS_JSON >> ./api_key.json
            ls
            cat ./gradle.properties
            cat ./api_key.json


  android-alpha:
    working_directory: /home/circleci/project/android
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout:
          path: /home/circleci/project

      - attach_workspace:
          at: /home/circleci/project

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane android alpha
          command: |
            bundle update fastlane
            bundle exec fastlane alpha

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk

  android-beta:
    working_directory: /home/circleci/project/android
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout:
          path: /home/circleci/project

      - attach_workspace:
          at: /home/circleci/project

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane android beta
          command: |
            bundle exec fastlane beta

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android-alpha:
          requires:
            - node